# Generated by Django 2.1.3 on 2018-12-06 09:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=40, verbose_name='Название абонемента')),
                ('slug', models.SlugField(default=None, max_length=150, unique=True, verbose_name='URL страницы')),
                ('price', models.DecimalField(decimal_places=2, default=None, max_digits=10, verbose_name='Цена абонемента')),
                ('body', ckeditor.fields.RichTextField(default=None, verbose_name='Описание абонемента')),
                ('img', models.ImageField(blank=True, default='product_default.jpg', help_text='Необязательное поле', upload_to='products_image', verbose_name='Фоновая картинка')),
            ],
            options={
                'verbose_name': 'Абонемент',
                'verbose_name_plural': 'Абонементы',
            },
        ),
    ]
