# Generated by Django 2.1.7 on 2019-02-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=40, verbose_name='Название купона')),
                ('discount', models.PositiveIntegerField(default=None, verbose_name='Размер скидки')),
                ('description', models.TextField(blank=True, verbose_name='Описание купона')),
            ],
            options={
                'verbose_name': 'Купон',
                'verbose_name_plural': 'Купоны',
            },
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kids_name', models.CharField(default=None, max_length=30, verbose_name='ФИО ученика')),
                ('cost', models.CharField(default=None, max_length=20, null=True, verbose_name='Сумма покупки')),
                ('qty', models.CharField(default=None, max_length=20, null=True, verbose_name='Количество абонементов')),
                ('name', models.CharField(default=None, max_length=30, null=True, verbose_name='ФИО плательщика')),
                ('email', models.CharField(default=None, max_length=30, null=True, verbose_name='Email')),
                ('tel', models.CharField(default=None, max_length=30, null=True, verbose_name='Номер телефона')),
                ('branches', models.CharField(max_length=70, null=True, verbose_name='Филиал')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.AddField(
            model_name='products',
            name='item_total',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=9),
        ),
        migrations.AddField(
            model_name='products',
            name='qty',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
    ]
