# Generated by Django 2.1.3 on 2019-02-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0003_auto_20190220_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='full_img',
            field=models.ImageField(blank=True, default='pay-detail-img.jpg', help_text='Необязательное поле', upload_to='products_image', verbose_name='Изображение в описании'),
        ),
    ]
