# Generated by Django 2.1.3 on 2019-02-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0004_auto_20190220_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='img',
            field=models.ImageField(blank=True, default='pay-detail-img.jpg', help_text='Необязательное поле', upload_to='products_image', verbose_name='Фоновое изображение'),
        ),
    ]
