# Generated by Django 2.1.3 on 2019-02-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0005_auto_20190220_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='crossed_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, verbose_name='Зачеркнутая цена абонемента'),
        ),
    ]
