# Generated by Django 2.1.3 on 2019-02-21 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0008_auto_20190221_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='crossed_price',
        ),
    ]
