# Generated by Django 2.1.3 on 2019-02-21 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0010_products_crossed_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='crossed_price',
        ),
    ]
