# Generated by Django 2.1.7 on 2019-02-21 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0014_products_crossed_price'),
        ('pay', '0002_auto_20190212_1238'),
    ]

    operations = [
    ]
