# Generated by Django 2.1.7 on 2019-02-21 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0015_merge_20190221_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='crossed_price',
        ),
    ]
