# Generated by Django 2.1.7 on 2019-02-21 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0017_products_crossed_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='full_img',
        ),
    ]
