# Generated by Django 2.1.7 on 2019-02-21 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0018_remove_products_full_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='full_img',
            field=models.ImageField(blank=True, default='pay-detail-img.jpg', help_text='Необязательное поле', upload_to='products_image', verbose_name='Изображение в описании'),
        ),
    ]
