# Generated by Django 2.1.7 on 2019-03-28 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0019_products_full_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='crossed_price',
        ),
        migrations.RemoveField(
            model_name='products',
            name='full_img',
        ),
    ]
