# Generated by Django 2.1.7 on 2019-03-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0020_auto_20190328_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='crossed_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name='Зачеркнутая цена абонемента'),
        ),
        migrations.AddField(
            model_name='products',
            name='full_img',
            field=models.ImageField(blank=True, default='pay-detail-img.jpg', help_text='Необязательное поле', upload_to='products_image', verbose_name='Изображение в описании'),
        ),
    ]
