# Generated by Django 2.1.7 on 2019-04-21 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0022_ordermodel_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='birth_date',
        ),
    ]
