# Generated by Django 2.1.7 on 2019-04-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0026_ordermodel_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='birth_date',
            field=models.CharField(blank=True, default='2000.01.01', max_length=30, verbose_name='Дата рождения'),
            preserve_default=False,
        ),
    ]
