# Generated by Django 2.1.7 on 2019-04-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0027_auto_20190421_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='kids_name2',
            field=models.CharField(default=None, max_length=30, verbose_name='ФИО ученика2'),
        ),
    ]
