# Generated by Django 2.1.7 on 2019-04-22 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0002_auto_20190422_1500'),
        ('pay', '0033_ordermodel_birth_date'),
    ]

    operations = [
    ]
