# Generated by Django 2.1.7 on 2019-04-22 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0034_merge_20190422_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='crossed_price',
        ),
    ]
