# Generated by Django 2.2.1 on 2019-06-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0037_remove_ordermodel_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='birth_date',
            field=models.CharField(default='Не указано', max_length=30, verbose_name='Дата рождения'),
        ),
    ]
