# Generated by Django 2.2.1 on 2019-06-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0038_ordermodel_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='abon',
            field=models.CharField(default='Не указано', max_length=30, null=True, verbose_name='Тип абонемента'),
        ),
    ]
