# Generated by Django 2.2.1 on 2019-08-27 08:37

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0063_auto_20190818_1430'),
        ('pay', '0039_ordermodel_abon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Абонемент', 'verbose_name_plural': 'Общие абонементы'},
        ),
        migrations.CreateModel(
            name='CityProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=40, verbose_name='Название абонемента')),
                ('slug', models.SlugField(default=None, max_length=150, unique=True, verbose_name='URL страницы')),
                ('price', models.DecimalField(decimal_places=2, default=None, max_digits=10, verbose_name='Цена абонемента')),
                ('crossed_price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name='Зачеркнутая цена абонемента')),
                ('body', ckeditor.fields.RichTextField(default=None, verbose_name='Описание абонемента')),
                ('img', models.ImageField(blank=True, default='pay-detail-img.jpg', help_text='Необязательное поле', upload_to='products_image', verbose_name='Фоновое изображение')),
                ('full_img', models.ImageField(blank=True, default='pay-detail-img.jpg', help_text='Необязательное поле', upload_to='products_image', verbose_name='Изображение в описании')),
                ('qty', models.PositiveIntegerField(default=1, editable=False)),
                ('item_total', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=9)),
                ('product_city', models.ForeignKey(default='Город не выбран', on_delete=django.db.models.deletion.CASCADE, to='pixel.Cities', verbose_name='Город абонемента')),
            ],
            options={
                'verbose_name': 'Абонемент',
                'verbose_name_plural': 'Уникальные абонементы',
            },
        ),
    ]
