# Generated by Django 2.2.1 on 2019-08-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0040_auto_20190827_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityproducts',
            name='slug',
            field=models.SlugField(default=None, max_length=150, unique=True, verbose_name='URL страницы (автозаполнение)'),
        ),
    ]
