# Generated by Django 2.1.2 on 2018-11-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20181111_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='thumb',
            field=models.ImageField(blank=True, default='/static/img/default.jpg', upload_to=''),
        ),
    ]
