# Generated by Django 2.1.2 on 2018-11-11 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20181111_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='thumb',
        ),
    ]
