# Generated by Django 2.1.2 on 2018-11-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_remove_news_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='thumb',
            field=models.ImageField(blank=True, default='/static/img/default.jpg', upload_to=''),
        ),
    ]
