# Generated by Django 2.1.2 on 2018-11-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_news_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=60, verbose_name='Заголовок'),
        ),
    ]
