# Generated by Django 2.1.2 on 2018-11-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupmodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата записи'),
        ),
    ]
