# Generated by Django 2.1.2 on 2018-11-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_signupmodel_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signupmodel',
            options={'verbose_name': 'Запись', 'verbose_name_plural': 'Список записей на занятия'},
        ),
        migrations.AlterField(
            model_name='signupmodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата заявки'),
        ),
        migrations.AlterField(
            model_name='signupmodel',
            name='email',
            field=models.EmailField(max_length=30, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='signupmodel',
            name='kid_age',
            field=models.CharField(max_length=30, verbose_name='Возраст ребенка'),
        ),
        migrations.AlterField(
            model_name='signupmodel',
            name='kid_name',
            field=models.CharField(max_length=30, verbose_name='Имя ребенка'),
        ),
        migrations.AlterField(
            model_name='signupmodel',
            name='message',
            field=models.CharField(max_length=30, verbose_name='Дополнительная информация'),
        ),
        migrations.AlterField(
            model_name='signupmodel',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='signupmodel',
            name='surname',
            field=models.CharField(max_length=30, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='signupmodel',
            name='tel',
            field=models.CharField(max_length=30, verbose_name='Номер телефона'),
        ),
    ]
