# Generated by Django 2.1.2 on 2018-11-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0005_auto_20181127_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupmodel',
            name='branches',
            field=models.CharField(default=None, max_length=50, verbose_name='Филиал'),
        ),
    ]
