# Generated by Django 2.1.2 on 2018-11-27 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0006_signupmodel_branches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupmodel',
            name='branches',
            field=models.CharField(max_length=50, verbose_name='Филиал'),
        ),
    ]
