# Generated by Django 2.1.2 on 2018-11-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0008_auto_20181127_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupmodel',
            name='branches',
            field=models.CharField(max_length=50, null=True, verbose_name='Филиал'),
        ),
    ]
