# Generated by Django 2.1.2 on 2018-11-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0009_auto_20181127_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupmodel',
            name='branches',
            field=models.CharField(max_length=70, null=True, verbose_name='Филиал'),
        ),
    ]
