# Generated by Django 2.1.2 on 2018-12-02 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0010_auto_20181128_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupmodel',
            name='email',
            field=models.EmailField(max_length=30, verbose_name='Email'),
        ),
    ]
