# Generated by Django 2.1.3 on 2019-05-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0011_auto_20181202_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='branches',
            name='name',
            field=models.CharField(default='Не задано', max_length=100, verbose_name='Название филиала'),
        ),
        migrations.AddField(
            model_name='branches',
            name='yandex_adr',
            field=models.CharField(default='Не задан', help_text='Точный адрес для поиска здания на картах Яндекса', max_length=100, verbose_name='Адрес филила для Яндекса'),
        ),
    ]
