# Generated by Django 2.1.3 on 2019-05-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0012_auto_20190502_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branches',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название филиала'),
        ),
        migrations.AlterField(
            model_name='branches',
            name='yandex_adr',
            field=models.CharField(help_text='Точный адрес для поиска здания на картах Яндекса', max_length=100, verbose_name='Адрес филила для Яндекса'),
        ),
    ]
