# Generated by Django 2.1.3 on 2019-05-02 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0034_questions'),
        ('signup', '0013_auto_20190502_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='branches',
            name='city',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pixel.Cities', verbose_name='Город, в котором находится филиал'),
        ),
    ]
