# Generated by Django 2.1.3 on 2019-05-02 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0015_auto_20190502_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branches',
            name='city',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='pixel.Cities', verbose_name='Город, в котором находится филиал'),
        ),
    ]
