# Generated by Django 2.1.3 on 2019-05-02 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0019_branches_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branches',
            old_name='city',
            new_name='branch_city',
        ),
    ]
