# Generated by Django 2.1.3 on 2019-05-02 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0022_branches_branch_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branches',
            name='branch_city',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='pixel.Cities', verbose_name='Город, в котором находится филиал'),
        ),
    ]
