# Generated by Django 2.2.1 on 2019-05-30 11:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0025_branches_branch_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='branches',
            name='body',
            field=ckeditor.fields.RichTextField(default=None, verbose_name='Содержимое метки'),
        ),
    ]
