# Generated by Django 2.2.1 on 2019-05-30 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0027_auto_20190530_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branches',
            name='body',
        ),
    ]
