# Generated by Django 2.2.1 on 2019-05-30 11:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0028_remove_branches_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='branches',
            name='body',
            field=ckeditor.fields.RichTextField(default=None, null=True, verbose_name='Содержимое метки'),
        ),
    ]
