# Generated by Django 2.2.1 on 2019-05-30 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0030_auto_20190530_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branches',
            name='description_url',
            field=models.URLField(default=None, null=True, verbose_name='Ссылка внутри метки на карте'),
        ),
    ]
