# Generated by Django 2.2.1 on 2019-08-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0032_auto_20190818_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupmodel',
            name='branches',
            field=models.CharField(max_length=200, null=True, verbose_name='Филиал'),
        ),
        migrations.AlterField(
            model_name='signupmodel',
            name='email',
            field=models.EmailField(max_length=200, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='signupmodel',
            name='kid_age',
            field=models.CharField(max_length=200, verbose_name='Дата рождения ученика'),
        ),
        migrations.AlterField(
            model_name='signupmodel',
            name='kid_name',
            field=models.CharField(max_length=200, verbose_name='ФИО ученика'),
        ),
        migrations.AlterField(
            model_name='signupmodel',
            name='name',
            field=models.CharField(max_length=200, verbose_name='ФИО контактного лица'),
        ),
        migrations.AlterField(
            model_name='signupmodel',
            name='service',
            field=models.CharField(default='Запись на пробное занятие', max_length=200, verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='signupmodel',
            name='tel',
            field=models.CharField(max_length=200, verbose_name='Номер телефона'),
        ),
    ]
