# Generated by Django 2.2.1 on 2019-08-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0033_auto_20190818_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupmodel',
            name='email',
            field=models.CharField(max_length=200, verbose_name='Email'),
        ),
    ]
