# Generated by Django 2.2.1 on 2019-08-27 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0034_auto_20190818_1656'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signupmodel',
            options={'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
    ]
