# Generated by Django 2.2.1 on 2019-09-03 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0063_auto_20190818_1430'),
        ('signup', '0035_auto_20190827_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название филиала')),
                ('tel', models.CharField(max_length=100, verbose_name='Телефон')),
                ('email', models.CharField(max_length=100, verbose_name='Почта, на которую будут приходить заявки')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pixel.Cities', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Франшиза',
                'verbose_name_plural': 'Франшизы',
            },
        ),
    ]
