# Generated by Django 2.2.1 on 2019-09-03 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0038_franchise'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Franchise',
        ),
    ]
