# Generated by Django 2.2.1 on 2019-09-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0039_delete_franchise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('tel', models.CharField(max_length=100, verbose_name='Телефон')),
                ('email', models.CharField(max_length=100, verbose_name='Почта, на которую будут приходить заявки')),
                ('adr', models.CharField(max_length=200, verbose_name='Адрес')),
                ('coords', models.CharField(help_text='Для определения координат точки, используйте сервис https://yandex.ru/map-constructor/location-tool/. Пример: [55.4325,37.5498]', max_length=100, verbose_name='Координаты')),
                ('zoom', models.IntegerField(help_text='Можно определить через тот же сервис в поле "Масштаб"', max_length=10, verbose_name='Масштаб')),
                ('yandex_adr', models.CharField(help_text='Точный адрес для поиска здания на картах Яндекса', max_length=100, verbose_name='Адрес филила для Яндекса')),
                ('description_url', models.URLField(verbose_name='Ссылка внутри метки на карте')),
                ('flag', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Франшиза',
                'verbose_name_plural': 'Франшизы',
            },
        ),
    ]
