# Generated by Django 2.2.1 on 2019-09-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0063_auto_20190818_1430'),
        ('signup', '0040_franchise'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchise',
            name='courses',
            field=models.ManyToManyField(to='pixel.Courses', verbose_name='Курсы в этом филиале'),
        ),
    ]
