# Generated by Django 2.1.7 on 2019-04-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ФИО контактного лица')),
                ('tel', models.CharField(max_length=30, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=30, verbose_name='Email')),
                ('kids_name', models.CharField(max_length=50, verbose_name='ФИО ученика')),
                ('message', models.CharField(max_length=70, verbose_name='Выбранный приз')),
                ('branches', models.CharField(max_length=200, null=True, verbose_name='Филиал')),
                ('date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата заявки')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Список заявок на получение приза',
            },
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название документа')),
                ('flag', models.CharField(default='None', max_length=100, verbose_name='Метка документа')),
                ('file', models.FileField(upload_to='', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='SeoEngine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=50, verbose_name='Страница')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок страницы')),
                ('description', models.TextField(max_length=300, verbose_name='Описание страницы')),
                ('keywords', models.CharField(max_length=300, verbose_name='Ключевые слова')),
            ],
            options={
                'verbose_name': 'SEO настройки страницы',
                'verbose_name_plural': 'SEO настройки страниц сайта',
            },
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.CharField(default=None, max_length=60, verbose_name='Название слайдера'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title1',
            field=models.CharField(blank=True, default='None', help_text='Если заголовок не нужен, оставьте поле пустым', max_length=60, verbose_name='Заголовок 1-го слайда'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title2',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Заголовок 2-го слайда'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title3',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Заголовок 3-го слайда'),
        ),
    ]
