# Generated by Django 2.1.2 on 2018-11-13 16:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True, verbose_name='Описание абонемента'),
        ),
        migrations.AddField(
            model_name='products',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
