# Generated by Django 2.1.2 on 2018-11-13 16:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0002_auto_20181113_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='body',
            field=ckeditor.fields.RichTextField(default=None, verbose_name='Описание абонемента'),
        ),
    ]
