# Generated by Django 2.1.2 on 2018-12-02 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0004_auto_20181113_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ФИО контактного лица')),
                ('tel', models.CharField(max_length=30, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=30, verbose_name='Email')),
                ('kids_name', models.CharField(max_length=50, verbose_name='ФИО ученика')),
                ('message', models.CharField(max_length=50, verbose_name='Выбранный приз')),
                ('branches', models.CharField(max_length=70, null=True, verbose_name='Филиал')),
                ('date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата заявки')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Список заявок на получение приза',
            },
        ),
    ]
