# Generated by Django 2.1.2 on 2018-12-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0005_bonusmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonusmodel',
            name='email',
            field=models.EmailField(max_length=30, unique=True, verbose_name='Email'),
        ),
    ]
