# Generated by Django 2.1.2 on 2018-12-02 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0006_auto_20181202_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonusmodel',
            name='message',
            field=models.CharField(max_length=70, verbose_name='Выбранный приз'),
        ),
    ]
