# Generated by Django 2.1.2 on 2018-12-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0007_auto_20181202_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonusmodel',
            name='email',
            field=models.EmailField(max_length=30, verbose_name='Email'),
        ),
    ]
