# Generated by Django 2.1.7 on 2019-04-22 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0008_auto_20181202_1222'),
        ('pixel', '0002_auto_20190422_1502'),
    ]

    operations = [
    ]
