# Generated by Django 2.1.3 on 2019-04-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0010_cities'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='details_button1_text',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='Кнопка подробнее'),
        ),
        migrations.AddField(
            model_name='slider',
            name='details_button1_url',
            field=models.URLField(default=None, verbose_name='Ссылка для кнопки'),
        ),
        migrations.AddField(
            model_name='slider',
            name='details_button2_text',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='Кнопка подробнее'),
        ),
        migrations.AddField(
            model_name='slider',
            name='details_button2_url',
            field=models.URLField(default=None, verbose_name='Ссылка для кнопки'),
        ),
        migrations.AddField(
            model_name='slider',
            name='details_button3_text',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='Кнопка подробнее'),
        ),
        migrations.AddField(
            model_name='slider',
            name='details_button3_url',
            field=models.URLField(default=None, verbose_name='Ссылка для кнопки'),
        ),
    ]
