# Generated by Django 2.1.3 on 2019-04-24 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0013_auto_20190424_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='details_button1_url',
        ),
    ]
