# Generated by Django 2.1.3 on 2019-04-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0014_remove_slider_details_button1_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='details_button1_url',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='Ссылка для кнопки'),
        ),
    ]
