# Generated by Django 2.1.7 on 2019-04-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0030_cities_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='help_text',
            field=models.CharField(editable=False, max_length=100, verbose_name='Какие курсы доступны в этом городе?'),
        ),
    ]
