# Generated by Django 2.1.3 on 2019-05-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0033_auto_20190427_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Вопрос')),
                ('request_text', models.TextField(verbose_name='Ответ на вопрос')),
                ('column_choice', models.CharField(choices=[('left', 'Левая'), ('right', 'Правая')], max_length=30, verbose_name='Выберите колонку')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Ответы на часто задаваемые вопросы',
            },
        ),
    ]
