# Generated by Django 2.1.3 on 2019-05-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0034_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='cities',
            name='leto_mindstorms',
            field=models.BooleanField(default=False, verbose_name='Летние курсы Mindstorms'),
        ),
        migrations.AddField(
            model_name='cities',
            name='leto_wedo',
            field=models.BooleanField(default=False, verbose_name='Летние курсы WeDo'),
        ),
    ]
