# Generated by Django 2.1.3 on 2019-05-14 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0035_auto_20190514_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cities',
            name='leto_mindstorms',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='leto_wedo',
        ),
    ]
