# Generated by Django 2.1.3 on 2019-05-15 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0040_callbacks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callbacks',
            options={'verbose_name': 'Заявку', 'verbose_name_plural': 'Заявки на звонок'},
        ),
    ]
