# Generated by Django 2.2.1 on 2019-05-29 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0043_auto_20190529_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cities',
            name='coords',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='zoom',
        ),
    ]
