# Generated by Django 2.2.1 on 2019-05-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0045_auto_20190529_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='coords',
            field=models.CharField(default=None, help_text='Для определения координат точки, используйте сервис https://yandex.ru/map-constructor/location-tool/. Пример: [55.4325,37.5498]', max_length=100, null=True, verbose_name='Координаты'),
        ),
    ]
