# Generated by Django 2.2.1 on 2019-05-29 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0046_auto_20190529_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='zoom',
            field=models.IntegerField(default=None, help_text='Можно определить через тот же сервис в поле "Масштаб"', max_length=10, null=True, verbose_name='Масштаб'),
        ),
    ]
