# Generated by Django 2.2.1 on 2019-07-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0049_cities_kodu'),
    ]

    operations = [
        migrations.AddField(
            model_name='cities',
            name='unity3d',
            field=models.BooleanField(default=False, verbose_name='Unity3D'),
        ),
    ]
