# Generated by Django 2.2.1 on 2019-08-02 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0052_auto_20190802_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='age_max',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='age_min',
        ),
    ]
