# Generated by Django 2.2.1 on 2019-08-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0053_auto_20190802_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='age_max',
            field=models.IntegerField(default=None, null=True, verbose_name='Максимальный возраст учеников'),
        ),
        migrations.AddField(
            model_name='courses',
            name='age_min',
            field=models.IntegerField(default=None, null=True, verbose_name='Минимальный возраст учеников'),
        ),
    ]
