# Generated by Django 2.2.1 on 2019-08-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0055_cities_courses_in_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cities',
            name='courses_in_city',
        ),
        migrations.AddField(
            model_name='cities',
            name='courses_in_city',
            field=models.ManyToManyField(default=None, null=True, to='pixel.Courses', verbose_name='Укажите курсы в этом городе'),
        ),
    ]
