# Generated by Django 2.2.1 on 2019-08-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0056_auto_20190802_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='courses_in_city',
            field=models.ManyToManyField(default=None, null=True, to='pixel.Courses', verbose_name='Выберите какие курсы доступны в этом городе'),
        ),
    ]
