# Generated by Django 2.2.1 on 2019-08-02 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0057_auto_20190802_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cities',
            name='arduino',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='kinder',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='kodu',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='leto_mindstorms',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='leto_wedo',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='mindstorms',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='mindstormspro',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='minecraft',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='scratch',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='unity3d',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='wedo',
        ),
    ]
