# Generated by Django 2.2.1 on 2019-08-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0059_auto_20190802_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='btn_color',
            field=models.CharField(choices=[('Желтый', 'Желтый'), ('Синий', 'Синий'), ('Красный', 'Красный')], default=None, max_length=50, null=True, verbose_name='Выберите цвет кнопки'),
        ),
    ]
