# Generated by Django 2.2.1 on 2019-08-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0060_auto_20190802_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='url',
            field=models.URLField(default=None, null=True, verbose_name='Ссылка на подробное описание курса'),
        ),
    ]
