# Generated by Django 2.2.1 on 2019-08-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0061_courses_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='bg_image',
            field=models.ImageField(default='default_courses_bg.png', help_text='385 px на 531 px', upload_to='courses_image', verbose_name='Фоновое изображение'),
        ),
    ]
