# Generated by Django 2.2.1 on 2019-08-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0062_auto_20190802_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='courses_in_city',
            field=models.ManyToManyField(default=None, null=True, to='pixel.Courses', verbose_name='Курсы в этом городе'),
        ),
    ]
