# Generated by Django 2.2.1 on 2019-09-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0064_auto_20190903_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_left', models.CharField(max_length=200, verbose_name='Имя сотрудника')),
                ('role_left', models.CharField(max_length=200, verbose_name='Занимаемая должность сотрудника')),
                ('photo_left', models.ImageField(default='default_photo.jpg', upload_to='team_photos', verbose_name='Фото сотрудника')),
                ('name_middle', models.CharField(max_length=200, verbose_name='Имя сотрудника')),
                ('role_middle', models.CharField(max_length=200, verbose_name='Занимаемая должность сотрудника')),
                ('photo_middle', models.ImageField(default='default_photo.jpg', upload_to='team_photos', verbose_name='Фото сотрудника')),
                ('name_right', models.CharField(max_length=200, verbose_name='Имя сотрудника')),
                ('role_right', models.CharField(max_length=200, verbose_name='Занимаемая должность сотрудника')),
                ('photo_right', models.ImageField(default='default_photo.jpg', upload_to='team_photos', verbose_name='Фото сотрудника')),
            ],
            options={
                'verbose_name': 'Слайд с сотрудниками',
                'verbose_name_plural': 'Команда',
            },
        ),
    ]
