# Generated by Django 2.2.1 on 2019-09-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0065_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='photo_left',
            field=models.ImageField(default='default_photo.jpg', help_text='Размер фото 228x228. Формат PNG. Форма круга с вырезанным фоном', upload_to='team_photos', verbose_name='Фото сотрудника'),
        ),
        migrations.AlterField(
            model_name='team',
            name='photo_middle',
            field=models.ImageField(default='default_photo.jpg', help_text='Размер фото 228x228. Формат PNG. Форма круга с вырезанным фоном', upload_to='team_photos', verbose_name='Фото сотрудника'),
        ),
        migrations.AlterField(
            model_name='team',
            name='photo_right',
            field=models.ImageField(default='default_photo.jpg', help_text='Размер фото 228x228. Формат PNG. Форма круга с вырезанным фоном', upload_to='team_photos', verbose_name='Фото сотрудника'),
        ),
    ]
