# Generated by Django 2.2.1 on 2019-09-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0067_feedbacks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacks',
            name='feedback_text',
            field=models.TextField(verbose_name='Текст отзыва'),
        ),
        migrations.AlterField(
            model_name='feedbacks',
            name='feedback_title',
            field=models.CharField(max_length=200, verbose_name='Заголовок отзыва'),
        ),
    ]
