# Generated by Django 2.2.1 on 2019-09-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0068_auto_20190920_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacks',
            name='client_photo',
            field=models.ImageField(default='default-fb-photo.png', upload_to='feedback_clients_photos', verbose_name='Фото клиента'),
        ),
    ]
