# Generated by Django 2.2.1 on 2019-09-23 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0069_auto_20190923_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbacks',
            name='client_photo',
        ),
    ]
