# Generated by Django 2.2.1 on 2019-09-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0071_feedbacks_client_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacks',
            name='client_photo',
            field=models.ImageField(default='/media/default-fb-photo.png', upload_to='feedback_clients_photos', verbose_name='Фото клиента'),
        ),
    ]
